### ISSUE TITLE
#2 add ssl-proxy server to the launcher

### ISSUE THREAD

**Issue by TaKeO90** [TaKeO90/pwm#8]

**Comment by TaKeO90** [comment]
I have no clue i start playing with ```github.com/malikbenkirane/ssl-proxy``` , even though i import the cert to the browser i cannot access the web page without facing this following problem ```This server could not prove that it is 0.0.0.0; its security certificate is from localhost``` . so i still trying to figure out how i can make it work .

**Comment by malikbenkirane** [comment]
Look at main.go there's an undocumented option named altnames in the flags
that should solve your issue.

**Comment by malikbenkirane** [comment]
Feel free to make a PR for the docs.

**Comment by TaKeO90** [comment]
Oh my bad i saw that flag when i was looking to the changes you've  made to that  repo but i didn't read the code to understand what it did :(  again that was my bad .
