### ISSUE TITLE
#3 setup a Dockerfile for the project 

### ISSUE THREAD

**Issue by TaKeO90** [TaKeO90/pwm#9]
for convient way to use the program we need to launch it using docker. to launch the frontend and the backend and expose their port .

**Comment by malikbenkirane** [comment]
Use a docker file to build images for each service. Don't start with docker-compose or thinking of ports. You should also document yourself on kubernetes services, deployments first :
- https://kubernetes.io/docs/concepts/services-networking/
- https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by TaKeO90** [comment]
OK Thank you
